# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target '定位功能的实现' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'BaiduMapKit'
  # Pods for 定位功能的实现

end
